### ISSUE TITLE
Can't run on mac because of apples weird permissions

### ISSUE THREAD

**Issue by Ccode-lang** [vlang/py2v#8]
The terminal output is.

```
  File "ast2json.py", line 33
    print(f'USAGE: {sys.argv[0]} <source> <destination>')
                                                       ^
SyntaxError: invalid syntax
V panic: optional not set (failed to open file "/tmp/ast2json.temp.json")
v hash: d0100fa
0   libdyld.dylib                       0x000000018548d450 start + 4
```
Haven't looked into the code much so I have no idea what this means.  
  
  
Also, I don't know how to read v errors.
  
  
Looks like it can't open the file or can't find it. I do know this project creates a file in /tmp. I checked it's not there.

**Comment by div72** [comment]
@Ccode-lang What's your default python version?

**Comment by div72** [comment]
Could you check if 2f3dcb9b6d1f9eebc4df32e8ff60f0d30c5c8167 fixes the issue?

**Comment by Ccode-lang** [comment]
Python 2 on my mac

**Comment by Ccode-lang** [comment]
I'll try

**Comment by Ccode-lang** [comment]
I've had problems with macs permissions in my projects to though and I usually use python3.  I do have python3 installed to though

**Comment by Ccode-lang** [comment]
Your change works, thanks!
